# Makefile for Amazon Linux 2 (non-static build)
# Use this if static linking fails: make -f Makefile.amazon_linux2

CXX = g++
TARGET = glue
BINDIR	= ${HOME}/.glue/bin/
# Removed --static flag for better compatibility
CXXFLAGS = -Wall -O2 -std=c++17
LDFLAGS = -lm
SRCS := $(wildcard *.cc)
OBJS := $(SRCS:.cc=.o)

$(TARGET): $(OBJS)
	$(CXX) -o $@ $(OBJS) $(LDFLAGS)
	cp $(TARGET) ../

.PHONY: clean
clean:
	rm -f $(TARGET) $(OBJS)
	rm -f $(TARGET)

install: $(TARGET)
	install -m 755 $(CURDIR)/$(TARGET) $(BINDIR)/$(TARGET)

uninstall:
	rm $(BINDIR)/$(TARGET)
